services:
    contao.hooks.get_cache_key:
        class: Contao\CoreBundle\EventListener\Hook\GetCacheKeyListener
        tags:
            - { name: kernel.event_listener, event: contao.get_cache_key, method: onGetCacheKey }

    contao.hooks.initialize_system:
        class: Contao\CoreBundle\EventListener\Hook\InitializeSystemListener
        tags:
            - { name: kernel.event_listener, event: contao.initialize_system, method: onInitializeSystem }

    contao.hooks.parse_backend_template:
        class: Contao\CoreBundle\EventListener\Hook\ParseBackendTemplateListener
        tags:
            - { name: kernel.event_listener, event: contao.parse_backend_template, method: onParseBackendTemplate }

    contao.hooks.parse_frontend_template:
        class: Contao\CoreBundle\EventListener\Hook\ParseFrontendTemplateListener
        tags:
            - { name: kernel.event_listener, event: contao.parse_frontend_template, method: onParseFrontendTemplate }
